### ISSUE TITLE
Binary files cannot be translated correctly on Raspberry PI

### ISSUE THREAD

**Issue by lixin123321** [aengelke/instrew#10]
Binary files cannot be translated correctly on Raspberry PI：illegal instruction

**Comment by aengelke** [comment]
Please provide more details on: input binary file, command, output, details on the fault (in JIT-compiled code or elsewhere, address, surrounding code, relevant object file if JIT-compiled), etc.

**Comment by lixin123321** [comment]
Sorry for the late reply.
I compiled a static hello file on the Raspberry PI, but when I executed this hello file via instrew, the command line says "illegal instructions"
When I debug with gdb, it says "Thread 1.1 "instrew-client" received signal SIGILL, illegal instruction"
