### ISSUE TITLE
unable to translate binary from x86_64 to Aarch64

### ISSUE THREAD

**Issue by Stephen-lei** [aengelke/instrew#19]
Hello, i am using instrew to translate Spec 2006 from x86_64 to Aarch64(dynamic linked). and it shows the following error:

```
(base) admin@ampere:~/test/SPEC2006/bzip2$ ~/instrew/instrew/build/server/instrew ./bzip2 input.combined 80
error: could not load file
error: expected C_INIT message
```
i guess it is because i have not specific the corss platfrom glibc for x86_64 on Aarch64. for qemu, it is a commd 
`qemu-x86_64 -L /usr/x86_64-linux-gnu/ ...`
i want to know is there any same command for instrew? thank you very much!

**Comment by aengelke** [comment]
As a quick fix, you can link statically. You could also run specify the loader explitly (`instrew /usr/x86_64-linux-gnu/lib/ld-linux-x86-64.so.2 ./bzip2 ...`; adjust the name to your system) and adjust the LD_LIBRARY_PATH properly. Alternatively, you could try chroot. There is no `-L` for Instrew at this point.

**Comment by Stephen-lei** [comment]
thank you very much! after i specify the loader and set the LD_LIBRARY_PATH, it works。
