### ISSUE TITLE
crash on aarch64

### ISSUE THREAD

**Issue by jiangning-liu-ampere** [aengelke/instrew#6]
Hi, I got this error message. The host architecture is aarch64 and the OS is fedora36. Any idea?

===========

 ./build/server/instrew /bin/ls -l
unhandled syscall 167 (17 20 0 400050d51f50 400050d52340 400050cffd00) = -ENOSYS -- please file a bug with these numbers and the architecture
unhandled syscall 43 (400050d20428 400050cffc50 400050d40060 0 400050d067f0 400050cffd00) = -ENOSYS -- please file a bug with these numbers and the architecture
unhandled syscall 98 (400050f218cc 81 7fffffff 0 4 0) = -ENOSYS -- please file a bug with these numbers and the architecture
The futex facility returned an unexpected error code.
Aborted (core dumped)

**Comment by younghojan** [comment]
Hi, when I benchmark Instrew with SPEC CPU 2017 on aarch64, I also encountered these problems. I emailed the developer months ago and he replied 

"That indicates that the program wants to use a syscall where the emulation isn't implemented yet. I changed Instrew to just warn instead of aborting execution."

Hopes this help!

**Comment by Aqua-Peak** [comment]
Me too. I want to run x86_64 spec2006 on host aarch64. Result shows that syscall named fork, clone  in emulate_syscall() do not be supportted. Without these syscall  , the author how to run spec2017.

**Comment by younghojan** [comment]
> Me too. I want to run x86_64 spec2006 on host aarch64. Result shows that syscall named fork, clone in emulate_syscall() do not be supportted. Without these syscall , the author how to run spec2017.

refer to:

https://github.com/aengelke/instrew/issues/9

**Comment by lijiansong** [comment]
Is there qemu system mode support for [instrew](https://github.com/aengelke/instrew)?
Seems instrew only support user mode?

**Comment by aengelke** [comment]
> Seems instrew only support user mode?

Yes.

**Comment by Aqua-Peak** [comment]
Instrew only support user mode.来自横渠的邮件在 2024年1月4日，17:13，Json Lee ***@***.***> 写道：﻿
Is there qemu system mode support for instrew?
Seems instrew only support user mode?
